pipeline:
  deps:
    image: gitea.nulo.in/nulo/super-image:3.18
    commands:
      - pnpm install
  build:
    image: gitea.nulo.in/nulo/super-image:3.18
    group: build
    commands:
      - pnpm build
  check:
    image: gitea.nulo.in/nulo/super-image:3.18
    group: build
    commands:
      - pnpm check
  upload:
    image: gitea.nulo.in/nulo/super-image:3.18
    commands:
      - |
        eval $(ssh-agent -s)
        echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        echo "[nulo.ar]:2223 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQEuHNIWQcS5La6lc2OvHQxZN6tRVtkts2wH1tfpola" > ~/.ssh/known_hosts

      - scp -rP2223 dist/* root@nulo.ar:/data/beta_schreiben_nulo_ar/
    when:
      branch: antifascista
      event: push
    secrets:
      - ssh_key