pipeline:
  deps:
    image: gitea.nulo.in/nulo/super-image:3.17
    commands:
      - pnpm install
  build:
    image: gitea.nulo.in/nulo/super-image:3.17
    group: build
    commands:
      - pnpm build
  check:
    image: gitea.nulo.in/nulo/super-image:3.17
    group: build
    commands:
      - pnpm check
  upload:
    image: gitea.nulo.in/nulo/super-image:3.17
    commands:
      - |
        eval $(ssh-agent -s)
        echo "$${SSH_KEY}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        echo "[nulo.ar]:993 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHgHIbf5/jkeyLMndnWlEO12DPj41YPqkmz+aIreVOsP" > ~/.ssh/known_hosts

      - scp -rP993 dist/* ci-schreiben@nulo.ar:/var/www/beta.schreiben.nulo.ar/
    when:
      branch: antifascista
      event: push
    secrets:
      - ssh_key